language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"

# don't add osx, python not supported
os:
  - linux

# no need for pytest, travis already has it
install:
  - pip install .

script:
  - make test
  - make test-examples
  - make benchmark

addons:
  apt:
    packages:
      - graphviz
