language: python
python:
  - "2.7"

os:
  - linux
  - osx

# no need for pytest, travis already has it
install:
  - pip install -r requirements_py27.txt

script:  python -m pytest

addons:
  apt:
    packages:
      - graphviz

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update          ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install graphviz; fi
