language: python
python:
  - "2.7"

os:
  - linux

# no need for pytest, travis already has it
install:
  - pip install -r requirements.txt

script:  make test

addons:
  apt:
    packages:
      - graphviz
