language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"

# don't add osx, python not supported
os:
  - linux

install:
  - pip install .
  - pip install -r tests/requirements.txt

script:
  - make test
  - make test-examples
  - make benchmark
  - make cov

addons:
  apt:
    packages:
      - graphviz
